// device-detector/agora-detector-vue/src/steps/CameraDetecting.vue
<template>
  <PageContainer>
    <template v-slot:main>
        <div :class="styles['video-container']"
          ref="cameraVideo"></div>
        <div :class="styles['tab-title']">Camera Detection</div>
    </template>
    <template v-slot:bottom>
      <DeviceDetect
        v-if="deviceStep==='DETECTING'"
        text="Detecting..."
      />
      <DeviceAsk v-else-if="deviceStep==='ASK'"
        askText="Can you see the picture?"
        @handleClickNo="handleClickNo"
        @handleClickYes="handleClickYes"
        :btnDisabled="btnDisabled"
      />
      <DeviceAsk v-else-if="deviceStep==='RETRY'"
        askText="Do you want to replace the device and redetect?"
        @handleClickNo="handleClickRetryNo"
        @handleClickYes="handleClickRetryYes"
      />
      <DeviceSwitch v-else-if="deviceStep==='SWITCH'"
        :deviceItems="deviceItems"
        v-model="currentDevice"
        @change="handleSelectChange"
        @handleClickSwitchNo="handleClickSwitchNo"
        @handleClickSwitchYes="handleClickSwitchYes"
        :btnDisabled="btnDisabled"
      />
    </template>
  </PageContainer>
</template>

<script lang="ts">
import {
  Component, Vue, Prop, Watch,
} from 'vue-property-decorator';
import { IAgoraRTC, ICameraVideoTrack } from 'agora-rtc-sdk-ng';
import eventBus from '../utils/eventBus';
import Ring from '../components/Ring.vue';
import PageContainer from '../components/PageContainer.vue';
import Select from '../components/Select.vue';
import { SelectItem } from '../types/types';
import { wait } from '../utils/helper';
import DeviceAsk from '../components/commonDetect/DeviceAsk.vue';
import DeviceDetect from '../components/commonDetect/DeviceDetect.vue';
import DeviceSwitch from '../components/commonDetect/DeviceSwitch.vue';
import styles from '../styles.module.css';

@Component({
  components: {
    Ring,
    PageContainer,
    Select,
    DeviceAsk,
    DeviceDetect,
    DeviceSwitch,
  },
})
export default class CameraDetecting extends Vue {
  @Prop() private state!: string;

  @Prop() private deviceStep!: string;

  private cameraDevices: MediaDeviceInfo[] = [];

  private currentDevice: SelectItem = { value: null, label: 'Null' };

  private styles = styles;

  get deviceItems(): SelectItem[] {
    return this.cameraDevices.map((device) => ({
      value: device.deviceId,
      label: device.label,
    }));
  }

  @Watch('deviceStep')
  onDeviceStepChanged(newVal: string) {
    if (newVal === 'DETECTING') {
      this.detectCountDown();
    }
  }

  private btnDisabled = false;

  private handleClickNo() {
    eventBus.$emit('click-camera-ask-no');
    const cameraResult = eventBus.$data.getStore().get('cameraResult');
    cameraResult.result = false;
    eventBus.$data.getStore().set('cameraResult', cameraResult);
  }

  private handleClickYes() {
    eventBus.$emit('click-camera-ask-yes');
  }

  private handleClickRetryNo() {
    eventBus.$emit('click-camera-retry-no');
  }

  private async handleClickRetryYes() {
    this.btnDisabled = true;
    eventBus.$emit('click-camera-retry-yes');
    try {
      await this.getDevices();
    } finally {
      this.btnDisabled = false;
    }
  }

  private async getDevices() {
    const AgoraSDK = eventBus.$data.getStore().get('agoraSDK') as IAgoraRTC;
    try {
      this.cameraDevices = await AgoraSDK.getCameras();
    } catch (e) {
      console.error(e);
    }
    return this.deviceItems;
  }

  private handleClickSwitchNo() {
    eventBus.$emit('click-camera-switch-no');
  }

  private handleClickSwitchYes() {
    eventBus.$emit('click-camera-switch-yes');
  }

  private async handleSelectChange() {
    console.log('select change', this.currentDevice);
    this.btnDisabled = true;
    try {
      const cameraTrack = await eventBus.$data.getStore().get('trackManager').getCameraTrack() as ICameraVideoTrack;
      cameraTrack.setDevice(this.currentDevice.value);
    } finally {
      this.btnDisabled = false;
    }
  }

  async mounted() {
    const cameraTrack = await eventBus.$data.getStore().get('trackManager').getCameraTrack();
    cameraTrack && cameraTrack.play(this.$refs.cameraVideo);
    this.detectCountDown();
  }

  async detectCountDown() {
    const cameraTrack = await eventBus.$data.getStore().get('trackManager').getCameraTrack();
    const [result, , deviceItems] = await Promise.all([
      eventBus.$data.getStore().get('trackManager').checkCameraTrack(cameraTrack),
      wait(2000),
      this.currentDevice.value === null ? this.getDevices() : Promise.resolve(),
    ]);
    const newCurrentDevice = deviceItems && deviceItems[0];
    if (newCurrentDevice) {
      this.currentDevice = newCurrentDevice;
    }
    if (!result) {
      this.$emit('showCameraTips');
    }
    eventBus.$data.getStore().set('cameraResult', {
      deviceLabel: this.currentDevice.label,
      deviceId: this.currentDevice.value,
      result,
    });
    eventBus.$emit('camera-detect-finish');
  }
}
</script>

// device-detector/agora-detector-react/src/steps/CameraDetecting.tsx
import * as React from 'react';
import PageContainer from '../components/PageContainer';
import styles from '../styles.module.css';
import eventBus from '../utils/eventBus';
import DeviceSwitch from '../components/commonDetect/DeviceSwitch';
import DeviceDetect from '../components/commonDetect/DeviceDetect';
import { DeviceStepState, DeviceItem } from '../types';
import { wait } from '../utils/helper';
import DeviceAsk from '../components/commonDetect/DeviceAsk';

interface Props {
  deviceStep: DeviceStepState;
  onShowCameraTips: Function;
}

export const CameraDetecting = ({ deviceStep, onShowCameraTips }: Props) => {
  const [currentDevice, setCurrentDevice] = React.useState<DeviceItem>();

  const [deviceItems, setDeviceItems] = React.useState<DeviceItem[]>([]);

  const cameraVideo = React.useRef<HTMLDivElement>(null);

  const [btnDisabled, setBtnDisabled] = React.useState(false);

  const [isFirstRender, setIsFirstRender] = React.useState(true);

  React.useEffect(() => {
    if (!eventBus.data.trackManager) {
      throw new Error('trackManager is not found');
    }
    eventBus.data.trackManager.getCameraTrack().then((track) => {
      if (!track) return;
      const cameraTrack = track;
      if (!cameraVideo.current) {
        throw new Error('can not get Video DOM');
      }
      cameraTrack && cameraTrack.play(cameraVideo.current);
    });
    setIsFirstRender(false);
    detectCountDown();
  }, []);

  React.useEffect(() => {
    if (!isFirstRender && deviceStep === 'DETECTING') {
      detectCountDown();
    }
  }, [deviceStep]);

  const handleClickNo = () => {
    eventBus.emit('click-camera-ask-no');
    const cameraResult = eventBus.data.cameraResult;
    if (cameraResult) {
      cameraResult.result = false;
    }
    eventBus.data.cameraResult = cameraResult;
  };

  const handleClickYes = () => {
    eventBus.emit('click-camera-ask-yes');
  };

  const handleClickRetryYes = async () => {
    setBtnDisabled(true);
    eventBus.emit('click-camera-retry-yes');
    try {
      await getDevices();
    } finally {
      setBtnDisabled(false);
    }
  };

  const handleClickRetryNo = () => {
    eventBus.emit('click-camera-retry-no');
  };

  const handleClickSwitchNo = () => {
    eventBus.emit('click-camera-switch-no');
  };

  const handleClickSwitchYes = () => {
    eventBus.emit('click-camera-switch-yes');
  };

  const handleSelectChange = async (item: DeviceItem) => {
    setCurrentDevice(item);
    try {
      setBtnDisabled(true);
      if (!eventBus.data.trackManager) return;
      const cameraTrack = await eventBus.data.trackManager.getCameraTrack();
      if (!cameraTrack)
        throw new Error('cannot find camera track to set device');
      cameraTrack.setDevice(item.value);
    } finally {
      setBtnDisabled(false);
    }
  };

  const getDevices = async () => {
    const AgoraSDK = eventBus.data.agoraSDK;
    if (!AgoraSDK) return;
    let newDeviceItems;
    try {
      const cameraDevices = await AgoraSDK.getCameras();
      newDeviceItems = cameraDevices.map((device) => ({
        value: device.deviceId,
        label: device.label
      }));
      setDeviceItems(newDeviceItems);
    } catch (e) {
      console.error(e);
    }
    return newDeviceItems;
  };

  const detectCountDown = async () => {
    if (!eventBus.data.trackManager) return;
    const cameraTrack = await eventBus.data.trackManager.getCameraTrack();
    const taskList: Promise<any>[] = [wait(2000)];
    cameraTrack &&
      taskList.push(eventBus.data.trackManager.checkCameraTrack(cameraTrack));
    if (!currentDevice || !currentDevice.value) {
      taskList.push(getDevices());
    }
    const [, result, newDeviceItems] = await Promise.all(taskList);
    const newCurrentDevice = newDeviceItems && newDeviceItems[0];
    newCurrentDevice && setCurrentDevice(newCurrentDevice);
    const deviceForResult = newCurrentDevice || currentDevice;
    if (!deviceForResult) {
      throw new Error(
        `check video track failed. currentDevice: ${deviceForResult}, result: ${result}`
      );
    }
    if (!result) {
      onShowCameraTips();
    }
    eventBus.data.cameraResult = {
      deviceLabel: deviceForResult.label,
      deviceId: deviceForResult.value,
      result
    };
    eventBus.emit('camera-detect-finish');
  };

  return (
    <PageContainer
      main={
        <React.Fragment>
          <div className={styles['video-container']} ref={cameraVideo} />
          <div className={styles['tab-title']}>Camera Detection</div>
        </React.Fragment>
      }
      bottom={
        <React.Fragment>
          {deviceStep === 'DETECTING' && <DeviceDetect text='Detecting...' />}
          {deviceStep === 'ASK' && (
            <DeviceAsk
              askText='Can you see the picture?'
              handleClickNo={handleClickNo}
              handleClickYes={handleClickYes}
            />
          )}
          {deviceStep === 'RETRY' && (
            <DeviceAsk
              askText='Do you want to replace the device and redetect?'
              handleClickYes={handleClickRetryYes}
              handleClickNo={handleClickRetryNo}
            />
          )}
          {deviceStep === 'SWITCH' && (
            <DeviceSwitch
              handleClickSwitchNo={handleClickSwitchNo}
              handleClickSwitchYes={handleClickSwitchYes}
              btnDisabled={btnDisabled}
              deviceItems={deviceItems}
              handleSelectChange={handleSelectChange}
              currentDevice={currentDevice || { value: null, label: 'null' }}
            />
          )}
        </React.Fragment>
      }
    />
  );
};

export default CameraDetecting;
