// device-detector/agora-detector-vue/src/components/commonDetect/DeviceSwitch.vue
<template>
  <div :class="styles['switch-bottom']">
    <Select
      :class="$style['camera-select']"
      :items="deviceItems"
      :currentItem="currentItem"
      @change="change"></Select>
    <div :class="styles['button-group']">
      <button :class="styles['button-no'] + ' ' + styles.btn"
        @click="handleClickSwitchNo"
        :disabled="btnDisabled">
        Skip
      </button>
      <button :class="styles['button-yes'] + ' ' + styles.btn"
        @click="handleClickSwitchYes"
        :disabled="btnDisabled">
        Detect
      </button>
    </div>
  </div>
</template>

<script lang="ts">
import {
  Component, Vue, Prop, Model,
} from 'vue-property-decorator';
import { SelectItem } from '../../types/types';
import Select from '../Select.vue';
import styles from '../../styles.module.css';

@Component({
  components: {
    Select,
  },
})
export default class DeviceSwitch extends Vue {
  @Prop() private btnDisabled!: boolean;

  @Prop() private deviceItems!: SelectItem[];

  @Prop() private handleSelectChange!: Function;

  @Model('change', { type: Object }) readonly currentItem!: SelectItem;

  private styles = styles;

  handleClickSwitchNo() {
    this.$emit('handleClickSwitchNo');
  }

  handleClickSwitchYes() {
    this.$emit('handleClickSwitchYes');
  }

  change(value: any) {
    this.$emit('change', value);
  }
}
</script>

<style module>
.camera-select {
  margin: 0 auto;
  margin-top: 15px;
}
</style>

// device-detector/agora-detector-react/src/components/commonDetect/DeviceSwitch.tsx
import * as React from 'react';
import styles from '../../styles.module.css';
import Select from '../Select';
import { DeviceItem } from '../../types';

interface Props {
  handleClickSwitchYes: Function;
  handleClickSwitchNo: Function;
  btnDisabled: boolean;
  deviceItems: DeviceItem[];
  handleSelectChange: Function;
  currentDevice: DeviceItem;
}
const DeviceSwitch = ({
  handleClickSwitchYes,
  handleClickSwitchNo,
  btnDisabled,
  deviceItems,
  handleSelectChange,
  currentDevice
}: Props) => {
  return (
    <React.Fragment>
      <Select
        items={deviceItems}
        currentDevice={currentDevice}
        change={handleSelectChange}
      />
      <div className={styles['button-group']}>
        <button
          className={styles['button-no'] + ' ' + styles.btn}
          onClick={() => {
            handleClickSwitchNo();
          }}
          disabled={btnDisabled}
        >
          Skip
        </button>
        <button
          className={styles['button-yes'] + ' ' + styles.btn}
          onClick={() => {
            handleClickSwitchYes();
          }}
          disabled={btnDisabled}
        >
          Detect
        </button>
      </div>
    </React.Fragment>
  );
};

export default DeviceSwitch;
