// device-detector/agora-detector-react/example/src/App.tsx
import React from 'react'
import AgoraSDK from 'agora-rtc-sdk-ng';

import { AgoraDetector, DetectResults } from 'agora-detector-react'
import 'agora-detector-react/dist/index.css'

const App = () => {
  const style = {
    margin: '20px 20px',
  }

  const onComplete = (report: DetectResults) => {
    console.log('detect completed', report);
  }
  return <div style={style}>
    <div style={ {margin: '20px'} }>React Example</div>
    <AgoraDetector AgoraSDK={AgoraSDK} onComplete={onComplete}/>
  </div>
}

export default App;

// device-detector/agora-detector-vue/localExample/App.vue
<template>
  <div id="app">
    <AgoraDetector class="detector"

      @onComplete="onComplete">
    </AgoraDetector>
  </div>
</template>

<script>
export default {
  name: 'app',
  methods: {
    onComplete(report) {
      console.log(report);
    },
  },
};
</script>

<style>
 #app {
   height: 1000px;
   margin: 0 auto;
   padding: 20px;
   background-color:burlywood;
 }
 .detector {
   margin: 0 auto;
   position: relative;
 }
</style>
