// device-detector/agora-detector-vue/src/components/Container.vue
<template>
  <div :class="styles['detector-container']">
    <div :class="$style['err-tips']" v-show="showCamTips">
      <div :class="$style['err-tips-text']">
        Your video input is detected as still!
      </div>
    </div>
    <div :class="$style['err-tips']" v-show="showMicTips" ref="micTips">
      <div :class="$style['err-tips-text']">
        Your volume input is detected too low!
      </div>
    </div>
    <initialPage v-if="state === 'IDLE'"></initialPage>
    <ReportPage v-if="state === 'FINISH'"></ReportPage>
    <template v-if="state === 'DETECTING'">
      <template v-if="device === 'CAMERA'">
        <CameraDetecting :deviceStep="deviceStep"
          @showCameraTips="handleShowCameraTips"></CameraDetecting>
      </template>
      <template v-if="device === 'MICROPHONE'">
        <MicDetecting :deviceStep="deviceStep" @showMicTips="handleShowMicTips"></MicDetecting>
      </template>
      <template v-if="device === 'SPEAKER'">
        <SpeakerDetecting :deviceStep="deviceStep"></SpeakerDetecting>
      </template>
    </template>
  </div>
</template>

<script lang="ts">
import { Component, Vue, Prop } from 'vue-property-decorator';
import CameraDetecting from '../steps/CameraDetecting.vue';
import initialPage from '../steps/InitialPage.vue';
import ReportPage from '../steps/ReportPage.vue';
import MicDetecting from '../steps/MicDetecting.vue';
import SpeakerDetecting from '../steps/SpeakerDetecting.vue';
import { DetectState, DeviceState, DeviceStepState } from '../types/types';
import styles from '../styles.module.css';

@Component({
  components: {
    CameraDetecting,
    initialPage,
    ReportPage,
    MicDetecting,
    SpeakerDetecting,
  },
})
export default class Container extends Vue {
  @Prop() private state!: DetectState;

  @Prop() private device!: DeviceState;

  @Prop() private deviceStep!: DeviceStepState;

  private showCamTips = false;

  private showMicTips = false;

  private styles = styles;

  handleShowCameraTips() {
    this.showCamTips = true;
    setTimeout(() => {
      this.showCamTips = false;
    }, 3000);
  }

  handleShowMicTips() {
    this.showMicTips = true;
    if (this.showCamTips) {
      (this.$refs.micTips as HTMLElement).style.top = '50px';
    } else {
      (this.$refs.micTips as HTMLElement).style.top = '15px';
    }
    setTimeout(() => {
      this.showMicTips = false;
    }, 3000);
  }
}
export { Container };
</script>

<style module>
.err-tips {
  position: absolute;
  right: 10px;
  top: 15px;
  padding: 8px 16px;
  background-color: #fbdbdbf1;
  color: #f55151;
  border-radius: 5px;
  z-index: 1;
  text-align: center;
  display: flex;
  align-items: center;
  transition: opacity .2s;
}
.err-tips-text {
  font-size: 13px;
  line-height: 13px;
  display: inline-block;
}
</style>

// device-detector/agora-detector-react/src/components/Container.tsx
import * as React from 'react';
import InitialPage from '../steps/InitialPage';
import ReportPage from '../steps/ReportPage';
import CameraDetecting from '../steps/CameraDetecting';
import MicDetecting from '../steps/MicDetecting';
import SpeakerDetecting from '../steps/SpeakerDetecting';
import { DetectState, DeviceState, DeviceStepState } from '../types/index';
import styles from '../styles.module.css';

interface Props {
  state: DetectState;
  device: DeviceState;
  deviceStep: DeviceStepState;
}

export const Container = ({ state, device, deviceStep }: Props) => {
  const [showCamTips, setShowCamTips] = React.useState(false);
  const [showMicTips, setShowMicTips] = React.useState(false);

  const micTipsEl = React.useRef<HTMLDivElement>(null);
  const handleShowCameraTips = () => {
    setShowCamTips(true);
    setTimeout(() => {
      setShowCamTips(false);
    }, 3000);
  };

  const handleShowMicTips = () => {
    setShowMicTips(true);
    if (showCamTips) {
      if (micTipsEl.current) micTipsEl.current.style.top = '50px';
    } else {
      if (micTipsEl.current) micTipsEl.current.style.top = '15px';
    }
    setTimeout(() => {
      setShowMicTips(false);
    }, 3000);
  };

  return (
    <div className={styles['detector-container']}>
      {showCamTips && (
        <div className={styles['err-tips']}>
          <div className={styles['err-tips-text']}>
            Your video input is detected as still!
          </div>
        </div>
      )}
      {showMicTips && (
        <div className={styles['err-tips']} ref={micTipsEl}>
          <div className={styles['err-tips-text']}>
            Your volume input is detected too low!
          </div>
        </div>
      )}
      {state === 'IDLE' && <InitialPage />}
      {state === 'FINISH' && <ReportPage />}
      {state === 'DETECTING' && device === 'CAMERA' && (
        <CameraDetecting
          deviceStep={deviceStep}
          onShowCameraTips={handleShowCameraTips}
        />
      )}
      {state === 'DETECTING' && device === 'MICROPHONE' && (
        <MicDetecting
          deviceStep={deviceStep}
          onShowMicTips={handleShowMicTips}
        />
      )}
      {state === 'DETECTING' && device === 'SPEAKER' && (
        <SpeakerDetecting deviceStep={deviceStep} />
      )}
    </div>
  );
};

export default Container;
