// device-detector/agora-detector-vue/src/components/PageContainer.vue
<template>
  <div :class="styles['detector-container']">
      <div :class="styles['detector-main']">
        <slot name="main"></slot>
      </div>
    <div :class="styles['detector-bottom']">
      <slot name="bottom"></slot>
    </div>
  </div>
</template>
<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import styles from '../styles.module.css';

@Component
export default class PageContainer extends Vue {
  private styles = styles;
}
</script>

// device-detector/agora-detector-react/src/components/PageContainer.tsx
import * as React from 'react';
import styles from '../styles.module.css';
interface Props {
  main: JSX.Element;
  bottom: JSX.Element;
}
const PageContainer = ({ main, bottom }: Props) => {
  return (
    <div className={styles['detector-container']}>
      <div className={styles['detector-main']}>{main}</div>
      <div className={styles['detector-bottom']}>{bottom}</div>
    </div>
  );
};

export default PageContainer;
