// device-detector/agora-detector-vue/src/components/Volume.vue
<template>
  <div :class="$style['detector-volume']">
      <div :class="{
          [$style['volume-block']]: true,
          [$style.active]: i / barNumArr.length < currentLevel
        }"
        v-for="(n, i) in barNumArr" :key="i">
      </div>
  </div>
</template>

<script lang="ts">
import { Component, Vue, Prop } from 'vue-property-decorator';

@Component
export default class Volume extends Vue {
  @Prop() private length!: number;

  @Prop() private currentLevel!: number;

  get barNum() {
    return Math.floor(this.length / 6 + 0.5);
  }

  get barNumArr() {
    const arr = [];
    for (let i = 0; i < this.barNum; i += 1) {
      arr[i] = 0;
    }
    return arr;
  }
}
</script>

<style module>

.detector-volume {
  display: flex;
  width: fit-content;
  margin: 0 auto;
  margin-top: 30px;
}
.volume-block {
  width: 3px;
  height: 18px;
  margin-left: 3px;
  background-color: #CCCCCC;
}
.volume-block.active {
  background-color: #44A2FC;
}
</style>

// device-detector/agora-detector-react/src/components/Volume.tsx
import * as React from 'react';
import styles from '../styles/volume.module.css';
interface Props {
  currentLevel: number;
  length: number;
}
const Volume = ({ currentLevel, length }: Props) => {
  const [barNumArr, setBarNumArr] = React.useState<number[]>([]);
  React.useEffect(() => {
    const barNum = Math.floor(length / 6 + 0.5);
    const arr = [];
    for (let i = 0; i < barNum; i += 1) {
      arr[i] = i;
    }
    setBarNumArr(arr);
  }, []);
  return (
    <div className={styles['detector-volume']}>
      {barNumArr.map((n) => (
        <div
          className={
            styles['volume-block'] +
            ' ' +
            (n / barNumArr.length < currentLevel ? styles['volume-active'] : '')
          }
          key={n}
        />
      ))}
      {/* <div :class="{ 'volume-block': true, 'active': i / barNumArr.length < currentLevel }"
        v-for="(n, i) in barNumArr" :key="i"></div> */}
    </div>
  );
};

export default Volume;
